nm bond: Fix preserving `all_slaves_active` option
When `all_slaves_active` was previously set via nmstate or NM, follow up
bond modification will fail with:

    NmstateNotImplementedError: Unsupported bond option: 'all_slaves_active'='0'

This is because the option returned by `_get_bond_options_from_profiles()` is
not canonicalized.

Expand the check to cover `1` and `0`.

Integration test case included.

Signed-off-by: Gris Ge <fge@redhat.com>