test: Pull the container image before run
The github action CI might hit error when trying to pull container image
for `podman run`:

    Error: writing blob: storing blob to file
    "/var/tmp/storage2845006379/1": happened during read: unexpected EOF

No luck on finding root cause of this.

To workaround that, use `podman pull <image_name>` before `podman run`,
and retry on failure of `podman pull` for 5 times.

Signed-off-by: Gris Ge <fge@redhat.com>