Integration test: Fix python 3 split() TypeError
The pytest will fail with this error when running
`tests/integration/preserve_ip_config_test.py` in python 3:

        TypeError: a bytes-like object is required, not 'str'

It's caused by difference between python 2 and 3 on split() action.
The In python 2, bytes.split() generate string. In python 3, bytes
cannot invoke `split()`. The fix would be using `bytes.decode('utf-8')`
to convert bytes to unicode in `testlib/cmd.py:exec_cmd()`.

Signed-off-by: Gris Ge <fge@redhat.com>