CI: Fix nested `podman run` on CentOS stream 10
For ipsec tests, we need to run podman inside of container, this will
fails when running CentOS stream 10 container on ubuntu 24.04 with
error:

    Error: configure storage: 'overlay' is not supported over overlayfs, a
    mount_program is required: backing file system is unsupported for this
    graph driver

To fix the issue, mounting `/var/lib/containers` to container would fix
the problem.

Signed-off-by: Gris Ge <fge@redhat.com>