nm.connection: create a new setting if cannot import
If Nmstate get `Nonetype` when trying to import an existing connectio
setting from a connection, it is creating a new setting instead of
crashing.

This is fixing the following error:

```
     def import_by_profile(self, profile, is_controller):
         base = profile.get_setting_connection()
         new = NM.SettingConnection.new()
 >       new.props.id = base.props.id
 E       AttributeError: 'NoneType' object has no attribute 'props'
```

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>