rpm: Fix SONAME in RHEL 9 build
In recent release of `rust-toolset-1.75.0-1.el9.noarch`, the rpm macro
`%cargo_build` changed to use `RUSTFLAGS` which override our changes to
`.cargo/config.toml` fix for c library SONAME. This cause rpm failuer
when installing `nmstate-devel` rpm:

     error: Failed dependencies:
        libnmstate.so()(64bit) is needed by
        nmstate-devel-2.2.23-0.alpha.20240116.c606aaf.el9.x86_64

There is no document for how to append RUSTFLAGS for RHEL/Fedora rpm
build system. This patch is just hack by using `_package_note_flags`
defined by `/usr/lib/rpm/macros.d/macros.rust-toolset`.

All RHEL/CentOS 9 test need rpm been installed, hence no extra test
required for this patch.

Signed-off-by: Gris Ge <fge@redhat.com>