nm infiniband: Fix error when applying with pre-exist IB profile
When create pkey over base interface which already has NM profile
exists, we got failure:

    ib_setting.props.p_key = ib_config[InfiniBand.PKEY]
    TypeError: Must be number, not str

This is cased by query function of infiniband is using string for pkey,
and then converted to integer in `pre_edit_validation_and_cleanup()`
before apply, but in `prepare_config()` for those interface not
desired/changed, we are using directly from query result. Then we got
pkey as string.

Fixed by invoking `pre_edit_validation_and_cleanup()` before create
infiniband NM setting.

This is found by test case `TestInfiniBand::test_create_and_remove_pkey_nic`.
No extra test case required.

Manually tested on Mellanox MT27800(mlx5_ib).

Signed-off-by: Gris Ge <fge@redhat.com>