Fix when NMSettingConnection has no interface_name
Issue:
    In Fedora 28 VM, `nmstatectl set ens3` might fail with

    ```
      File "/home/fge/Source/nmstate/libnmstate/nm/device.py", line 144, in
      get_device_by_name
          return client.get_device_by_iface(devname)
          TypeError: Argument 1 does not allow None as a value
    ```

Root cause:

    The NMSettingConnection is not using interface name for device
    selection(for example, is using mac address).

Fix:

    Set the interface name in the duplicated new profile before
    processing since we need to be explicit on which interface to be use
    for this profile.

Signed-off-by: Gris Ge <fge@redhat.com>