nm ethtool pause: Fix error when both autoneg true and rx/tx defined
When applying

```yaml
  pause:
    rx: true
    tx: true
    autoneg: true
```

we got error:

    libnmstate.error.NmstateInternalError: DbusConnectionError:
    org.freedesktop.NetworkManager.Settings.Connection.InvalidProperty:
    ethtool.pause-autoneg: pause-autoneg cannot be enabled when setting
    rx/tx options dbus:

Change the code to ignore rx/tx setting when autoneg set to True.

Integration test case included.

Signed-off-by: Gris Ge <fge@redhat.com>
(cherry picked from commit e39214056f155ba81ef83b0e08d92502310b5fec)