sriov: raise proper exception when SR-IOV parameter is not supported
Some SR-IOV parameters could be not supported by the device driver.
Nmstate must return a proper error message instead of a generic one.

```
libnmstate.error.NmstateLibnmError: Activate profile: eno1 failed:
reason=The device=eno1 does not support one or more of the SR-IOV parameters set.
```

Ref: https://bugzilla.redhat.com/1819588

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>