WIP: CI: Fix the rpmdb error when running in travis CI
Due to bug of rpm and overlay2:
    https://bugzilla.redhat.com/show_bug.cgi?id=1680124

In travis CI, the might fail with:

```
error: db5 error(2) from dbenv->open: No such file or directory
error: cannot open Packages index using db5 - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
```

https://travis-ci.com/github/nmstate/nmstate/jobs/302357321#L619

To fix this issue, installing `dnf-plugin-ovl` would solve this problem
as suggested in https://bugzilla.redhat.com/1213602 .

Signed-off-by: Gris Ge <fge@redhat.com>