nm.bridge, validator: raise that port vlan is not implemented
When raising inside the mainloop, nmstate was not doing the rollback
because the exception was being ignored. Please see error log below.

The NmstateNotImplementedError should be raised during validation and
not during activation.

```
Exception ignored in: <bound method _NmClient.__del__ of <libnmstate.nm.nmclient._NmClient object at 0x7fad76995b00>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py", line 287, in __del__
    "_NmClient.delete_client() should be explicitly called "
libnmstate.error.NmstateInternalError: _NmClient.delete_client() should be explicitly called before python GC clean up the object.
```

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>