nm: Sleep before retry activation
When activating below state, NetworkManager will fail with error:

    libnmstate.error.NmstateLibnmError: Activate profile
    uuid:2c8e8bc2-ee95-4ab5-8759-3a6a9a211004 iface:veth2 type: ethernet
    failed: error=nm-manager-error-quark: Connection 'veth2' is not
    available on device veth2 because device is strictly unmanaged (2)

```yml
---
interfaces:
- name: veth1
  type: veth
  state: up
  veth:
    peer: veth2
- name: veth2
  type: ethernet
  state: up
```

Sleep 5 seconds before retry activation will fix the problem.

Signed-off-by: Gris Ge <fge@redhat.com>