mptcp: Treat none as empty MPTCP flags in current state when verifying
When applying state with empty MPTCP address flags with auto IP, we got
error like:

    VerificationError: Verification failure:
    eth1.interface.mptcp.address-flags desire '[]', current 'null'

The root cause is current state during verify stage has mptcp section as
None when no IP address found, we should treat None mptcp as empty for
verification stage.

Integration test case included.

Resolves: https://issues.redhat.com/browse/RHEL-38607

Signed-off-by: Gris Ge <fge@redhat.com>