travis: fix rpmdb problem
Travis might fail with

```
error: db5 error(2) from dbenv->open: No such file or directory
error: cannot open Packages index using db5 - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
Error: non zero exit code: 1: OCI runtime error
```

According to https://github.com/dogtagpki/pki/blob/master/travis/pki-init.sh
also need to rebuild the dnf cache.

Added `RUN rpm --verifydb` to container file to make sure the container
images has to valid rpmdb.

Signed-off-by: Gris Ge <fge@redhat.com>