ActiveConnection: Handle uninitialized device
Handle `ActiveConnection._nmdev` being None. This should fix a Traceback
when the openvswitch service is not running:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libnmstate/nm/connection.py", line 226, in _active_connection_callback
    ac.devname, ac.reason
  File "/usr/lib/python3.6/site-packages/libnmstate/nm/active_connection.py", line 171, in devname
    return self._nmdev.get_iface()
AttributeError: 'NoneType' object has no attribute 'get_iface'

Signed-off-by: Till Maas <opensource@till.name>