bond: Fix removing mac-restricted bond
Given a bond cannot hold customized MAC address (active-backup mode with
`fail_over_mac: active`),
When applying desired state with full detail of this bond
Then nmstate will fail with error

```
NmstateValueError: MAC address cannot be specified in bond interface
along with fail_over_mac active on active backup mode
```

This is because nmstate incorrectly run validation on interface been
marked as `absent`.

Fixed by skipping validation on absent bond interface.

Integration test case included and marked as tier1.

Resolves: https://issues.redhat.com/browse/RHEL-102600

Signed-off-by: Gris Ge <fge@redhat.com>