ovs: Support interface level `other_config` (api break)
The Rust API changed:

    The `OvsBridgeBondConfig.other_config: Option<HashMap>` changed to
    `OvsBridgeBondConfig.ovs_db:  Option<OvsDbIfaceConfig>`

The YAML API changed:

    The `other_config` under ovs bond should be stored under `ovs-db`
    section, please check follow up example for detail.

Considering the interface level `other_config` never works in previous
release, this is API change is acceptable.

Example on `other_config` of OVS bridge:

```yml
interfaces:
- name: br0
  type: ovs-bridge
  state: up
  ovs-db:
    other_config:
      in-band-queue: '12'
  bridge:
    port:
    - name: eth1
    - name: ovs0
```

Example on `other_config` of OVS Bond:

```yml
- name: br0
  type: ovs-bridge
  state: up
  bridge:
    port:
    - name: bond1
      link-aggregation:
        mode: balance-slb
        ovs-db:
          other_config:
            bond-miimon-interval: "100"
        port:
          - name: eth2
          - name: eth1
```

Example on `other_config` of OVS interface:

```yml
- name: eth1
  type: ethernet
  state: up
  ovs-db:
    other_config:
      emc-insert-inv-prob: 90
```

We hide interface level `ovs-db` section if it is empty. This help us
supporting older NetworkManager where `other_config` is not supported
yet. User will get error when they apply above yaml on old
NetworkManager:

    NmstateError: DependencyError: Please upgrade NetworkManager for
    specified interface type: Connection(InvalidSetting):ovs-other-config:
    unknown setting name

Integration test case included.

Signed-off-by: Gris Ge <fge@redhat.com>