rpm: Fix `make rpm` failure in Fedora
Previously, without fix on SONAME[1], when installing rpm generated by
`make rpm`, Fedora will complains:

    error: Failed dependencies:
            libnmstate.so()(64bit) is needed by nmstate-devel

To fix the issue, we updated the nmstate.spec.in to hold:
    * Both Fedora and RHEL specific lines
    * Both official release and snapshot build(snapshot will use
      internet for crates.io access)

Tested on CentOS stream 9, Fedora 38 and Fedora Rawhide(40).

Also removed copr build for RHEL/CentOS 8 due to no usage.

Resolves: RHEL-5002

[1]: https://github.com/rust-lang/cargo/issues/5045

Signed-off-by: Gris Ge <fge@redhat.com>