test: Fix decode error for ipsec test
The ipsec test will fail at setup stage with error:

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 18:
    invalid start byte

This is because `ipsec showhostkey` command is using `latin1` encoding.

Fixed by try utf-8 first and fallback to `latin1` encoding.

Signed-off-by: Gris Ge <fge@redhat.com>