RPMs: Require python-setuptools
nmstatectl needs python-setuptools to import `pkg_resources`:
```
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

Signed-off-by: Till Maas <opensource@till.name>