nm dns: Support arbitrary DNS config
By using the `org.freedesktop.NetworkManager.GlobalDnsConfiguration`
DBUS API, we can modify the `/etc/resolve.conf` directly overriding DNS
settings in NM profiles/connections.

We use this as fallback method when we failed to store DNS into
interface profile. And a warning message will be shown as:

    Cannot store DNS to NetworkManager interface connection:
    NotImplementedError: Placing IPv4/IPv6 nameserver in the middle of
    IPv6/IPv4 nameservers is not supported yet

    Storing DNS to NetworkManager via global dns API, this will cause
    _all__ interface level DNS settings been ignored

This will not be used for `gen_conf` mode. User still get error when not
able to store DNS into interface profile.

Removed the xfail of integration test case for `ipv6+ipv4+ipv6` and
`ipv4+ipv6+ipv4` name server format.

Signed-off-by: Gris Ge <fge@redhat.com>