nm.applier: team interfaces must be considered as master
The team interface is a master interface so it must be activated in the
proper order. If not, nmstate could raise the following error:

```
libnmstate.error.NmstateLibnmError: Activate profile: eth1 failed:
reason=<enum NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED of type NM.ActiveConnectionStateReason>
<enum NM_DEVICE_STATE_REASON_DEPENDENCY_FAILED of type NM.DeviceStateReason>
```

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>