rust: use write! instead of format! to avoid extra allocation
This is fixing the following clippy warining:

```
error: `format!(..)` appended to existing `String`
   --> src/libnm_dbus/keyfile.rs:177:21
    |
177 | /                     ret +=
178 | |                         &format!("address{}={}/{}\n", index, address, prefix);
    | |_____________________________________________________________________________^
    |
    = help: consider using `write!` to avoid the extra allocation
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string
```

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>