automation: rebuild rpmdb if copr repo is being used
Travis might fail with

```
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed
Error: non zero exit code: 1: OCI runtime error
```

Rebuilding the rpmdb when copr repositories are being used should fix
this issue.

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>