ip: Fix routes on empty address
Nmstate fails when applying below state:

```yml
---
routes:
  config:
  - destination: 198.51.100.0/24
    metric: 150
    next-hop-interface: eth1
    table-id: 254
interfaces:
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      enabled: true
      address: []
```

The error message is:

    NmstateError: InvalidArgument: The next hop interface of desired Route
    'destination: 198.51.100.0/24 next-hop-interface: eth1 metric: 150
    table-id: 254' has been marked as IPv4 disabled

The root cause is nmstate try to set `ipv4.enabled` to false when got
empty address, this then lead to incorrect validation.

To fix this issue, removed the sanitize on setting `ipv4.enabled` to
false on empty address, but ignore `ipvX.enabled` in validation stage
when got empty IP address list.

Integration test case updated.

Signed-off-by: Gris Ge <fge@redhat.com>