nm ovs: Fix bug of editing existing OVS interface
When editing existing OVS interface, nmstate failed with
    AttributeError: 'SimpleConnection' object has no attribute
    'commit_changes_async'

The root cause is nm/applier failed to load existing profile using
the OVS port interface name when OVS port name changed to hash string.
The fix is correct the interface name before look up when facing OVS
port.

Integration test case added for changing MAC address of existing OVS
interface.

Signed-off-by: Gris Ge <fge@redhat.com>