cli: Fix control+c panic
When user want to hit `Control+C` during nmstatectl apply, there will be
a panic error:

    thread 'main' panicked at src/lib/query_apply/net_state.rs:46:12:
    Cannot start a runtime from within a runtime. This happens because a
    function (like `block_on`) attempted to block the current thread
    while the thread is being used to drive asynchronous tasks.

This is caused by running new `block_on` against checkpoint rollback
inside of async function.

Fixed by changed to
`NetworkState::checkpoint_rollback_async("").await?`.

To complex to code automatic integration test case, and very simple to
verify manually, hence no test code included.

Signed-off-by: Gris Ge <fge@redhat.com>