nm: Use activated connection when referring parent or controller
When a interface has multiple NM profiles, creating a VLAN or bridge
above it will get failure on

    libnmstate.error.NmstateInternalError: Manager(UnknownDevice):
    Failed to find a compatible device for this connection

The root cause of this is `use_uuid_for_controller_reference()` and
`use_uuid_for_parent_reference()` is searching all existing NM
connections if not desired, this might lead to nmstate choosing the
inactivate profile as parent/controller.

To fix it, patched `use_uuid_for_parent_reference()` and
`use_uuid_for_controller_reference()` to prefer activated NM profiles
over other existing ones.

Resolves: RHBZ#2202999

Signed-off-by: Gris Ge <fge@redhat.com>